name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: fedora:38

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        dnf install -y dnf-plugins-core
        dnf copr enable -y ttys3/my-fedora-packages
        dnf upgrade -y --refresh
        dnf install -y cargo rust gcc-c++ cmake make
        dnf install -y xapian-core xapian-core-libs xapian-core-devel
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
